In [1]:
import numpy as np

In [2]:
n=int(input("enter the number of nodes"))
graph_heu=np.zeros([n,n])
graph_path=np.zeros([n,n])
s = 1
p = 1
s=int(input("enter the first node: "))
p=int(input("enter the second node: "))
heu=float(input("enter the heuristics: "))
pat=int(input("enter the path: "))
while(s!=-1 and p!=-1 and p!=-1):
    graph_heu[s][p]=heu
    graph_heu[p][s]=heu
    graph_path[p][s]=pat
    graph_path[s][p]=pat
    s=int(input("enter the first node: "))
    p=int(input("enter the second node: "))
    heu=float(input("enter the heuristics: "))
    pat=int(input("enter the path: "))
print(graph_heu)
print(graph_path)
source=int(input("enter the source node: "))
dest=int(input("enter the dest node: "))

enter the number of nodes 7
enter the first node:  0
enter the second node:  1
enter the heuristics:  3
enter the path:  1
enter the first node:  0
enter the second node:  2
enter the heuristics:  5
enter the path:  1
enter the first node:  1
enter the second node:  2
enter the heuristics:  4
enter the path:  1
enter the first node:  2
enter the second node:  3
enter the heuristics:  4
enter the path:  1
enter the first node:  3
enter the second node:  5
enter the heuristics:  6
enter the path:  1
enter the first node:  1
enter the second node:  4
enter the heuristics:  3
enter the path:  1
enter the first node:  4
enter the second node:  6
enter the heuristics:  5
enter the path:  1
enter the first node:  3
enter the second node:  6
enter the heuristics:  7.11
enter the path:  0
enter the first node:  2
enter the second node:  6
enter the heuristics:  6
enter the path:  0
enter the first node:  1
enter the second node:  6
enter the heuristics:  7.11
enter the path:  0
enter the first 

[[0.   3.   5.   0.   0.   0.   0.  ]
 [3.   0.   4.   0.   3.   0.   7.11]
 [5.   4.   0.   4.   0.   0.   6.  ]
 [0.   0.   4.   0.   0.   6.   7.11]
 [0.   3.   0.   0.   0.   0.   5.  ]
 [0.   0.   0.   6.   0.   0.   0.  ]
 [0.   7.11 6.   7.11 5.   0.   0.  ]]
[[0. 1. 1. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 0.]
 [1. 1. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]]


enter the source node:  0
enter the dest node:  6


In [20]:
bw=int(input("enter the beam width: "))
trav=[]
path=[]
path.append([source])
count=0
k=1

enter the beam width:  2


In [22]:
if(count==0):
    list=[]
    for i in range(n):
        if(graph_path[source][i]!=0 and i!=source):
            list.append([count,source,graph_heu[dest][i],i])
    co=1
    for i in list:
        path.append([co,i[0],i[1],i[2],i[3]])
        co+=1
    for i in range(len(list)):
        for j in range(0,len(list)-i-1):
            if(list[j][3]<list[j+1][3]):
                temp=list[j+1]
                list[j+1]=list[j]
                list[j]=temp
    print(list)
    a=[]
    for i in list:
        a.append([k,i[0],i[1],i[2],i[3]])
        k+=1
    trav.append([0,a])
    count+=1

[[0, 0, 6.0, 2], [0, 0, 7.11, 1]]


In [13]:
flag=1
while(flag==0 or len(trav)==0):
    for i in trav[0]:
        if(trav[0][0]<=len(trav)):

[[1, 0, 0, 6.0, 2], [2, 0, 0, 7.11, 1]]


In [24]:
trav[0]

[0, [[1, 0, 0, 6.0, 2], [2, 0, 0, 7.11, 1]]]