In [35]:
import numpy as np
import sys

In [37]:
n=int(input("enter the number of nodes"))
graph_path=np.zeros([n,n])
s = 1
p = 1
s=int(input("enter the first node: "))
p=int(input("enter the second node: "))
pat=int(input("enter the path: "))
while(s!=-1 and p!=-1 and p!=-1):
    graph_path[p][s]=pat
    graph_path[s][p]=pat
    s=int(input("enter the first node: "))
    p=int(input("enter the second node: "))
    pat=int(input("enter the path: "))
print(graph_path)
source=int(input("enter the source node: "))
dest=int(input("enter the dest node: "))

enter the number of nodes 7
enter the first node:  0
enter the second node:  1
enter the path:  3
enter the first node:  0
enter the second node:  2
enter the path:  5
enter the first node:  1
enter the second node:  2
enter the path:  4
enter the first node:  2
enter the second node:  3
enter the path:  4
enter the first node:  3
enter the second node:  5
enter the path:  6
enter the first node:  1
enter the second node:  4
enter the path:  3
enter the first node:  4
enter the second node:  6
enter the path:  5
enter the first node:  -1
enter the second node:  -1
enter the path:  -1


[[0. 3. 5. 0. 0. 0. 0.]
 [3. 0. 4. 0. 3. 0. 0.]
 [5. 4. 0. 4. 0. 0. 0.]
 [0. 0. 4. 0. 0. 6. 0.]
 [0. 3. 0. 0. 0. 0. 5.]
 [0. 0. 0. 6. 0. 0. 0.]
 [0. 0. 0. 0. 5. 0. 0.]]


enter the source node:  0
enter the dest node:  6


In [38]:
trav=[]
path=[]
path.append([source])
count=0
k=1
ext_list=[]

In [39]:
if(count==0):
    ext_list.append(source)
    list=[]
    list1=[]
    for i in range(n):
        if(graph_path[source][i]!=0 and i!=source):
            list.append([count,source,graph_path[source][i],i])
            list1.append(i)
    list_copy=list.copy()
    for i in range(len(list)-1):
        for j in range(0,len(list)-i-1):
            if(list[j][2]>list[j+1][2]):
                temp=list[j+1]
                list[j+1]=list[j]
                list[j]=temp
    print(list)
    c=0
    for i in range(len(list)):
        print(i)
        trav.insert(c,[(list1.index(list[i][3]))+1,list[i][0],list[i][1],list[i][2],list[i][3]])
        path.append([k+i,list_copy[i][0],list_copy[i][1],list_copy[i][2],list_copy[i][3]])
        c+=1
    k+=len(list)
    count+=1

[[0, 0, 3.0, 1], [0, 0, 5.0, 2]]
0
1


In [40]:
ora=sys.maxsize
while(len(trav)!=0):
    while(trav[0][4] in ext_list):
        trav.remove(trav[0])
        if(len(trav)==0):
            break
    if(len(trav)!=0):
        ext_list.append(trav[0][4])
        print(ext_list)
        list=[]
        list1=[]
        for j in range(n):
            if(graph_path[trav[0][4]][j]!=0 and j!=source):
                list.append([trav[0][0],trav[0][4],graph_path[trav[0][4]][j]+trav[0][3],j])
                list1.append(j)
        length=trav[0][0]
        while(length>0):
            if(path[length][2] in list1 ):
                list.pop(list1.index(path[length][2]))
                list1.pop(list1.index(path[length][2]))
            length=path[length][1]
        c=0
        for i in range(len(list)):
            path.append([k+i,list[i][0],list[i][1],list[i][2],list[i][3]])
            if(dest!=list[i][3] and list[i][2]<ora and (list[1][3] not in ext_list)):
                trav.insert(c,[k+i,list[i][0],list[i][1],list[i][2],list[i][3]])
            else:
                if(ora>list[i][2]):
                    ora=list[i][2]
            c+=1
        k=k+len(list)
        for i in range(len(trav)-1):
            for j in range(0,len(trav)-i-1):
                if(trav[j][3]>trav[j+1][3]):
                    temp=trav[j+1]
                    trav[j+1]=trav[j]
                    trav[j]=temp
        trav.remove(trav[0])

[0, 1]
[0, 1, 2]
[0, 1, 2, 4]
[0, 1, 2, 4, 3]


In [41]:
print(path)

[[0], [1, 0, 0, 3.0, 1], [2, 0, 0, 5.0, 2], [3, 1, 1, 7.0, 2], [4, 1, 1, 6.0, 4], [5, 2, 2, 9.0, 1], [6, 2, 2, 9.0, 3], [7, 4, 4, 11.0, 6], [8, 6, 3, 15.0, 5]]


In [31]:
path_main=[]
n=len(path)-1
while(n>0):
    if dest==path[n][4]:
        d=[]
        d.append(dest)
        d.append(path[n][2])
        length=path[n][1]
        while(length>0):
            d.append(path[length][2])
            length=path[length][1]
        path_main.append(d)
    n=n-1
print(path_main)

[]


In [26]:
print(ora)

11.0
