In [68]:
import numpy as np

In [92]:
n=int(input("enter the number of nodes"))
graph=np.zeros([n,n])
s = 1
p = 1
s=int(input("enter the first node: "))
p=int(input("enter the second node: "))
while(s!=-1 and p!=-1):
    graph[s][p]=1
    graph[p][s]=1
    s=int(input("enter the first node: "))
    p=int(input("enter the second node: "))
    

enter the number of nodes 7
enter the first node:  0
enter the second node:  1
enter the first node:  0
enter the second node:  2
enter the first node:  1
enter the second node:  2
enter the first node:  1
enter the second node:  4
enter the first node:  4
enter the second node:  6
enter the first node:  2
enter the second node:  3
enter the first node:  3
enter the second node:  5
enter the first node:  -1
enter the second node:  -1


In [70]:
print(graph)

[[0. 1. 1. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 0.]
 [1. 1. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]]


In [93]:
source=int(input("enter the source node: "))
dest=int(input("enter the dest node: "))


enter the source node:  0
enter the dest node:  6


In [94]:
trav=[]
path=[]
path.append([source])
count=0
k=1

In [95]:
if(count==0):
    list=[]
    for i in range(n):
        if(graph[source][i]==1 and i!=source):
            list.append(i)
    trav.append([k,count,source,list])
    path.append([k,count,source,list])
    count+=1
    k+=1
print(path)

[[0], [1, 0, 0, [1, 2]]]


In [96]:
while(len(trav)!=0):
    for i in trav[0][3]:
        if(i!=dest):
            list=[]
            for j in range(n):
                if(graph[i][j]==1 and j!=source):
                    list.append(j)
            length=trav[0][0]
            while(length>0):
                print(list,path[length])
                if(path[length][2] in list):
                    list.remove(path[length][2])
                length=path[length][1]
            if(len(list)>0):
                path.append([k,trav[0][0],i,list])
                trav.append([k,trav[0][0],i,list])
                k=k+1
    trav.remove(trav[0])

[2, 4] [1, 0, 0, [1, 2]]
[1, 3] [1, 0, 0, [1, 2]]
[1, 3] [2, 1, 1, [2, 4]]
[3] [1, 0, 0, [1, 2]]
[1, 6] [2, 1, 1, [2, 4]]
[6] [1, 0, 0, [1, 2]]
[2, 4] [3, 1, 2, [1, 3]]
[4] [1, 0, 0, [1, 2]]
[2, 5] [3, 1, 2, [1, 3]]
[5] [1, 0, 0, [1, 2]]
[2, 5] [4, 2, 2, [3]]
[5] [2, 1, 1, [2, 4]]
[5] [1, 0, 0, [1, 2]]
[1, 6] [6, 3, 1, [4]]
[6] [3, 1, 2, [1, 3]]
[6] [1, 0, 0, [1, 2]]
[3] [7, 3, 3, [5]]
[] [3, 1, 2, [1, 3]]
[] [1, 0, 0, [1, 2]]
[3] [8, 4, 3, [5]]
[] [4, 2, 2, [3]]
[] [2, 1, 1, [2, 4]]
[] [1, 0, 0, [1, 2]]


In [97]:
print(path)

[[0], [1, 0, 0, [1, 2]], [2, 1, 1, [2, 4]], [3, 1, 2, [1, 3]], [4, 2, 2, [3]], [5, 2, 4, [6]], [6, 3, 1, [4]], [7, 3, 3, [5]], [8, 4, 3, [5]], [9, 6, 4, [6]]]


In [98]:
path_main=[]
n=len(path)-1
while(n>0):
    if dest in path[n][3]:
        d=[]
        d.append(dest)
        d.append(path[n][2])
        length=path[n][1]
        while(length>0):
            d.append(path[length][2])
            length=path[length][1]
        path_main.append(d)
    n=n-1
print(path_main)

[[6, 4, 1, 2, 0], [6, 4, 1, 0]]
