In [12]:
import numpy as np

In [13]:
n=int(input("enter the number of nodes"))
graph=np.zeros([n,n])
s = 1
p = 1
s=int(input("enter the first node: "))
p=int(input("enter the second node: "))
while(s!=-1 and p!=-1):
    graph[s][p]=1
    graph[p][s]=1
    s=int(input("enter the first node: "))
    p=int(input("enter the second node: "))
print(graph)
source=int(input("enter the source node: "))
dest=int(input("enter the dest node: "))

enter the number of nodes 10
enter the first node:  0
enter the second node:  1
enter the first node:  1
enter the second node:  5
enter the first node:  1
enter the second node:  3
enter the first node:  3
enter the second node:  4
enter the first node:  4
enter the second node:  7
enter the first node:  7
enter the second node:  9
enter the first node:  9
enter the second node:  6
enter the first node:  6
enter the second node:  8
enter the first node:  7
enter the second node:  5
enter the first node:  8
enter the second node:  2
enter the first node:  2
enter the second node:  0
enter the first node:  0
enter the second node:  5
enter the first node:  -1
enter the second node:  -1


[[0. 1. 1. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 1. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 1. 0. 0.]
 [1. 1. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 1. 1. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 1. 0. 0.]]


enter the source node:  0
enter the dest node:  6


In [14]:
trav=[]
path=[]
path.append([source])
count=0
k=1

In [15]:
if(count==0):
    list=[]
    for i in range(n):
        if(graph[source][i]==1 and i!=source):
            trav.append([k,count,source,i])
            path.append([k,count,source,i])
            k+=1
    count+=1
print(path)

[[0], [1, 0, 0, 1], [2, 0, 0, 2], [3, 0, 0, 5]]


In [16]:
while(len(trav)!=0):
    list=[]
    for j in range(n):
        if(graph[trav[0][3]][j]==1 and j!=source):
            list.append(j)
    length=trav[0][0]
    while(length>0):
        if(path[length][2] in list[1]):
            list.remove(path[length][2])
        length=path[length][1]
    if(len(list)>0):
        c=0
        for i in list:
            path.append([k,trav[c][0],trav[c][3],i])
            trav.insert(c,[k,trav[c][0],trav[c][3],i])
            print(trav)
            c+=1
            k=k+1
        if(dest in list):
            trav.clear()
            break
        else:
            trav.pop(c)
        print(trav)
    else:
        trav.remove(trav[0])

[[4, 1, 1, 3], [1, 0, 0, 1], [2, 0, 0, 2], [3, 0, 0, 5]]
[[4, 1, 1, 3], [5, 1, 1, 5], [1, 0, 0, 1], [2, 0, 0, 2], [3, 0, 0, 5]]
[[4, 1, 1, 3], [5, 1, 1, 5], [2, 0, 0, 2], [3, 0, 0, 5]]
[[6, 4, 3, 4], [4, 1, 1, 3], [5, 1, 1, 5], [2, 0, 0, 2], [3, 0, 0, 5]]
[[6, 4, 3, 4], [5, 1, 1, 5], [2, 0, 0, 2], [3, 0, 0, 5]]
[[7, 6, 4, 7], [6, 4, 3, 4], [5, 1, 1, 5], [2, 0, 0, 2], [3, 0, 0, 5]]
[[7, 6, 4, 7], [5, 1, 1, 5], [2, 0, 0, 2], [3, 0, 0, 5]]
[[8, 7, 7, 5], [7, 6, 4, 7], [5, 1, 1, 5], [2, 0, 0, 2], [3, 0, 0, 5]]
[[8, 7, 7, 5], [9, 7, 7, 9], [7, 6, 4, 7], [5, 1, 1, 5], [2, 0, 0, 2], [3, 0, 0, 5]]
[[8, 7, 7, 5], [9, 7, 7, 9], [5, 1, 1, 5], [2, 0, 0, 2], [3, 0, 0, 5]]
[[10, 9, 9, 6], [9, 7, 7, 9], [5, 1, 1, 5], [2, 0, 0, 2], [3, 0, 0, 5]]


In [17]:
print(path)

[[0], [1, 0, 0, 1], [2, 0, 0, 2], [3, 0, 0, 5], [4, 1, 1, 3], [5, 1, 1, 5], [6, 4, 3, 4], [7, 6, 4, 7], [8, 7, 7, 5], [9, 7, 7, 9], [10, 9, 9, 6]]


In [18]:
path_main=[]
n=len(path)-1
while(n>0):
    if dest==path[n][3]:
        d=[]
        d.append(dest)
        d.append(path[n][2])
        length=path[n][1]
        while(length>0):
            d.append(path[length][2])
            length=path[length][1]
        path_main.append(d)
    n=n-1
print(path_main)

[[6, 9, 7, 4, 3, 1, 0]]
