In [180]:
import numpy as np

In [271]:
n=int(input("enter the number of nodes"))
graph_heu=np.zeros([n,n])
graph_path=np.zeros([n,n])
s = 1
p = 1
s=int(input("enter the first node: "))
p=int(input("enter the second node: "))
heu=float(input("enter the heuristics: "))
pat=int(input("enter the path: "))
while(s!=-1 and p!=-1 and p!=-1):
    graph_heu[s][p]=heu
    graph_heu[p][s]=heu
    graph_path[p][s]=pat
    graph_path[s][p]=pat
    s=int(input("enter the first node: "))
    p=int(input("enter the second node: "))
    heu=float(input("enter the heuristics: "))
    pat=int(input("enter the path: "))

enter the number of nodes 7
enter the first node:  0
enter the second node:  1
enter the heuristics:  3
enter the path:  1
enter the first node:  0
enter the second node:  2
enter the heuristics:  5
enter the path:  1
enter the first node:  1
enter the second node:  2
enter the heuristics:  4
enter the path:  1
enter the first node:  2
enter the second node:  3
enter the heuristics:  4
enter the path:  1
enter the first node:  3
enter the second node:  5
enter the heuristics:  6
enter the path:  1
enter the first node:  1
enter the second node:  4
enter the heuristics:  3
enter the path:  1
enter the first node:  4
enter the second node:  6
enter the heuristics:  5
enter the path:  1
enter the first node:  3
enter the second node:  6
enter the heuristics:  7.11
enter the path:  0
enter the first node:  2
enter the second node:  6
enter the heuristics:  6
enter the path:  0
enter the first node:  1
enter the second node:  6
enter the heuristics:  7.11
enter the path:  0
enter the first 

In [272]:
print(graph_heu)
print(graph_path)
source=int(input("enter the source node: "))
dest=int(input("enter the dest node: "))

[[0.   3.   5.   0.   0.   0.   0.  ]
 [3.   0.   4.   0.   3.   0.   7.11]
 [5.   4.   0.   4.   0.   0.   6.  ]
 [0.   0.   4.   0.   0.   6.   7.11]
 [0.   3.   0.   0.   0.   0.   5.  ]
 [0.   0.   0.   6.   0.   0.   0.  ]
 [0.   7.11 6.   7.11 5.   0.   0.  ]]
[[0. 1. 1. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 0.]
 [1. 1. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]]


enter the source node:  0
enter the dest node:  6


In [273]:
trav=[]
path=[]
path.append([source])
count=0
k=1

In [274]:
if(count==0):
    list=[]
    list1=[]
    for i in range(n):
        if(graph_path[source][i]!=0 and i!=source):
            list.append([count,source,graph_heu[dest][i],i])
            list1.append(i)
    list_copy=list.copy()
    for i in range(len(list)-1):
        for j in range(0,len(list)-i-1):
            print(j)
            if(list[j][2]>list[j+1][2]):
                temp=list[j+1]
                list[j+1]=list[j]
                list[j]=temp
    print(list)
    c=0
    for i in range(len(list)):
        print(i)
        trav.insert(c,[(list1.index(list[i][3]))+1,list[i][0],list[i][1],list[i][2],list[i][3]])
        path.append([k+i,list_copy[i][0],list_copy[i][1],list_copy[i][2],list_copy[i][3]])
        c+=1
    k+=len(list)
    count+=1

0
[[0, 0, 6.0, 2], [0, 0, 7.11, 1]]
0
1


In [275]:
print(trav)
print(path)

[[2, 0, 0, 6.0, 2], [1, 0, 0, 7.11, 1]]
[[0], [1, 0, 0, 7.11, 1], [2, 0, 0, 6.0, 2]]


In [276]:
while(len(trav)!=0):
    print(trav[0])
    list=[]
    list1=[]
    for j in range(n):
        if(graph_path[trav[0][4]][j]!=0 and j!=source):
            list.append([trav[0][0],trav[0][4],graph_heu[j][dest],j])
            list1.append(j)
    print(list1)
    length=trav[0][0]
    while(length>0):
        if(path[length][2] in list1):
            list.pop(list1.index(path[length][2]))
            list1.pop(list1.index(path[length][2]))
        length=path[length][1]
    list_copy=list.copy()
    
    if(len(list)>0):
        for i in range(len(list)-1):
            for j in range(0,len(list)-i-1):
                if(list[j][2]>list[j+1][2]):
                    temp=list[j+1]
                    list[j+1]=list[j]
                    list[j]=temp
        c=0
        for i in range(len(list)):
            trav.insert(c,[k+list1.index(list[i][3]),list[i][0],list[i][1],list[i][2],list[i][3]])
            path.append([k+i,list_copy[i][0],list_copy[i][1],list_copy[i][2],list_copy[i][3]])
            print(trav)
            c+=1
        k=k+len(list)
        if(dest in list1):
            trav.clear()
            break
        else:
            trav.pop(c)
    else:
        trav.remove(trav[0])

[2, 0, 0, 6.0, 2]
[1, 3]
[[3, 2, 2, 7.11, 1], [2, 0, 0, 6.0, 2], [1, 0, 0, 7.11, 1]]
[[3, 2, 2, 7.11, 1], [4, 2, 2, 7.11, 3], [2, 0, 0, 6.0, 2], [1, 0, 0, 7.11, 1]]
[3, 2, 2, 7.11, 1]
[2, 4]
[[5, 3, 1, 5.0, 4], [3, 2, 2, 7.11, 1], [4, 2, 2, 7.11, 3], [1, 0, 0, 7.11, 1]]
[5, 3, 1, 5.0, 4]
[1, 6]
[[6, 5, 4, 0.0, 6], [5, 3, 1, 5.0, 4], [4, 2, 2, 7.11, 3], [1, 0, 0, 7.11, 1]]


In [277]:
path_main=[]
n=len(path)-1
while(n>0):
    if dest==path[n][4]:
        d=[]
        d.append(dest)
        d.append(path[n][2])
        print(d)
        length=path[n][1]
        while(length>0):
            d.append(path[length][2])
            print(d)
            length=path[length][1]
        path_main.append(d)
    n=n-1
print(path_main)

[6, 4]
[6, 4, 1]
[6, 4, 1, 2]
[6, 4, 1, 2, 0]
[[6, 4, 1, 2, 0]]


In [262]:
print(path[len(path)-1][4])

6


In [260]:
print(path)

[[0], [1, 0, 0, 7.11, 1], [2, 0, 0, 6.0, 2], [2, 2, 2, 7.11, 1], [3, 2, 2, 7.11, 3], [4, 2, 1, 6.0, 2], [5, 2, 1, 5.0, 4], [6, 5, 4, 0.0, 6]]


In [244]:
print(list1)

[1]
